# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller soundcloud-lib
    - name: Build with pyinstaller
      run: |
        pyinstaller --onefile --hidden-import sclib soundcloudify.py
    - name: Upload the built program to GitHub
      uses: actions/upload-artifact@2.1.0
      with:
        # Artifact name
        name: dist-build
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/soundcloudify.exe
